/*CREATE TABLE directories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, root TEXT);*/
CREATE TABLE IF NOT EXISTS files (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, dir TEXT NOT NULL, rootpath TEXT NOT NULL,
docnumber TEXT NOT NULL, rid TEXT NOT NULL, purchase_id TEXT NOT NULL, object TEXT, price REAL, customer_inn TEXT,
customer_name TEXT, facial_acc INTEGER NOT NULL);